before_script:
- export BUILD_SITE=true
#- export LIB_CI_SCRIPT=https://github.com/home1-oss/oss-build/raw/develop/src/main/ci-script/lib_ci.sh
- export LIB_CI_SCRIPT=http://gitlab.local:10080/home1-oss/oss-build/raw/develop/src/main/ci-script/lib_ci.sh
- export ORIGIN_REPO_SLUG=home1-oss/oss-lib-errorhandle

stages:
- analysis
- test_and_build
- deploy

sonar:
  stage: analysis
  script:
  - echo "on_analysis"
  - bash ci.sh analysis

on_every_push:
  artifacts:
    expire_in: 1 day
    untracked: true
  script:
  - bash ci.sh test_and_build
  stage: test_and_build

on_develop_push:
  dependencies:
  - on_every_push
  only:
  - develop
  script:
  - bash ci.sh publish_snapshot publish_maven_site
  stage: deploy

on_master_push:
  artifacts:
    paths:
    - "**/build/libs/*.jar"
  dependencies:
  - on_every_push
  only:
  - master
  script:
  - bash ci.sh publish_release publish_maven_site
  stage: deploy

on_release_tag:
  dependencies:
  - on_every_push
  only:
  - /^release.+$/
  script:
  - bash ci.sh publish_release_tag
  stage: deploy
